name: CI/CD

on:
  push:
    branches:
      - testfeatures

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Test project
        run: dotnet test

      - name: Build Docker image
        run: |
          docker build --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
             --build-arg SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
             --build-arg PFX_PASSWORD=${{ secrets.PFX_PASSWORD }} \
             -t phuchoang1910/webapp_htsv .
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push phuchoang1910/webapp_htsv

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker pull phuchoang1910/webapp_htsv:latest
            docker stop webapp_htsv || true
            docker rm webapp_htsv || true
            docker run --name webapp_htsv -d -p 80:80 -p 443:443 \
            -e "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -e "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" \
            -e "PFX_PASSWORD=${{ secrets.PFX_PASSWORD }}" \
                phuchoang1910/webapp_htsv:latest

